image: node:18-alpine

cache:
  paths:
  - node_modules/

stages:
  - sync-with-github
  - git-clone-lambda-code
  - npm-install
  - deploy

sync-with-github:
  stage: sync-with-github
  before_script:
    - apk add git
  script:
    - echo "sync GitHub"
    - git remote add github https://$ACCESS_TOKEN@github.com/olcortesb/mimic-sam.git
    - git checkout main
    - git status
    - git push github main

git-clone-lambda-code:
  stage: git-clone-lambda-code
  image: alpine
  before_script:
    - apk add git
  script:
    - git clone --depth=1 -b main https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.com/serverless4741110/lambdas-src repository
    - rm -rf source_code/.git
    - cd repository
    - rm LICENSE
    - rm README.md
  artifacts:
    paths:
      - repository

npm-install:
  stage: npm-install
  before_script:
    - ls
    - npm --version
  script:
    - cd repository/src
    - npm install
  artifacts:
    paths:
      - repository

deploy-test:
  image: node:18
  before_script:
    - apt-get update
    - apt-get install -y build-essential
    - npm install -g serverless
  script:
    - sls version
    - sls deploy --stage slsprod
  only:
  - feat/test-sls-v4

  # image: python:3.8
  # stage: deploy
  # before_script:
  #   - pip3 install awscli --upgrade
  #   - pip3 install aws-sam-cli --upgrade
  # script:
  #   - > 
  #     sam deploy --template-file template.yaml
  #     --stack-name sam-lab
  #     --region eu-central-1 
  #     --resolve-s3
  #     --capabilities CAPABILITY_IAM 
  #     --no-fail-on-empty-changeset 
